* fixed parse-config to set LD to gcc (not ld) - fixes dropbear 	  compilation on powerpc as well as most probably many of the 	  undefined reference to `__udivdi3' and friends during cross 	  compilation we know about since ancient ROCK times 	* added dropbear.cache